name: Ping APIs every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"   # Every 10 minutes
  # workflow_dispatch:        # Allow manual trigger

jobs:
  trigger-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Call API 1
        run: |
          curl -X GET "https://sixthsense-frontend.onrender.com/" \
          -H "Content-Type: application/json"

      - name: Call API 2
        run: |
          curl -X GET "https://sixthsense-1.onrender.com" \
          -H "Content-Type: application/json" \
          -d '{"source":"github-cron"}'
          

      # Add more APIs if needed
