name: Ping APIs every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  trigger-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Call Frontend
        run: |
          curl -I https://sixthsense-frontend.onrender.com/

      - name: Call Backend
        run: |
          curl -I https://sixthsense-1.onrender.com/
